package isocodes

import (
	"reflect"
	"testing"
)

func TestCurrencyCode_Flag(t *testing.T) {
	type tcase struct {
		code CurrencyCode
		want string
	}

	tests := map[string]tcase{
		"AED": {AED, "🇦🇪"},
		"AFN": {AFN, "🇦🇫"},
		"ALL": {ALL, "🇦🇱"},
		"AMD": {AMD, "🇦🇲"},
		"ANG": {ANG, "🇳🇱"},
		"AOA": {AOA, "🇦🇴"},
		"ARS": {ARS, "🇦🇷"},
		"AUD": {AUD, "🇦🇺"},
		"AWG": {AWG, "🇦🇼"},
		"AZN": {AZN, "🇦🇿"},
		"BAM": {BAM, "🇧🇦"},
		"BBD": {BBD, "🇧🇧"},
		"BDT": {BDT, "🇧🇩"},
		"BGN": {BGN, "🇧🇬"},
		"BHD": {BHD, ""},
		"BIF": {BIF, "🇧🇮"},
		"BMD": {BMD, "🇧🇲"},
		"BND": {BND, "🇧🇳"},
		"BOB": {BOB, "🇧🇴"},
		"BOV": {BOV, ""},
		"BRL": {BRL, "🇧🇷"},
		"BSD": {BSD, "🇧🇸"},
		"BTN": {BTN, ""},
		"BWP": {BWP, "🇧🇼"},
		"BYR": {BYR, ""},
		"BZD": {BZD, "🇧🇿"},
		"CAD": {CAD, "🇨🇦"},
		"CDF": {CDF, "🇨🇩"},
		"CHE": {CHE, ""},
		"CHF": {CHF, "🇨🇭"},
		"CHW": {CHW, ""},
		"CLF": {CLF, ""},
		"CLP": {CLP, "🇨🇱"},
		"CNY": {CNY, "🇨🇳"},
		"COP": {COP, "🇨🇴"},
		"COU": {COU, ""},
		"CRC": {CRC, "🇨🇷"},
		"CUC": {CUC, ""},
		"CUP": {CUP, ""},
		"CVE": {CVE, "🇨🇻"},
		"CZK": {CZK, "🇨🇿"},
		"DJF": {DJF, "🇩🇯"},
		"DKK": {DKK, "🇩🇰"},
		"DOP": {DOP, "🇩🇴"},
		"DZD": {DZD, "🇩🇿"},
		"EGP": {EGP, "🇪🇬"},
		"ERN": {ERN, ""},
		"ETB": {ETB, "🇪🇹"},
		"EUR": {EUR, "🇪🇺"},
		"FJD": {FJD, "🇫🇯"},
		"FKP": {FKP, "🇫🇰"},
		"GBP": {GBP, "🇬🇧"},
		"GEL": {GEL, "🇬🇪"},
		"GHS": {GHS, ""},
		"GIP": {GIP, "🇬🇮"},
		"GMD": {GMD, "🇬🇲"},
		"GNF": {GNF, "🇬🇳"},
		"GTQ": {GTQ, "🇬🇹"},
		"GYD": {GYD, "🇬🇾"},
		"HKD": {HKD, "🇭🇰"},
		"HNL": {HNL, "🇭🇳"},
		"HRK": {HRK, "🇭🇷"},
		"HTG": {HTG, "🇭🇹"},
		"HUF": {HUF, "🇭🇺"},
		"IDR": {IDR, "🇮🇩"},
		"ILS": {ILS, "🇮🇱"},
		"INR": {INR, "🇮🇳"},
		"IQD": {IQD, ""},
		"IRR": {IRR, ""},
		"ISK": {ISK, "🇮🇸"},
		"JMD": {JMD, "🇯🇲"},
		"JOD": {JOD, ""},
		"JPY": {JPY, "🇯🇵"},
		"KES": {KES, "🇰🇪"},
		"KGS": {KGS, "🇰🇬"},
		"KHR": {KHR, "🇰🇭"},
		"KMF": {KMF, "🇰🇲"},
		"KPW": {KPW, ""},
		"KRW": {KRW, "🇰🇷"},
		"KWD": {KWD, ""},
		"KYD": {KYD, "🇰🇾"},
		"KZT": {KZT, "🇰🇿"},
		"LAK": {LAK, "🇱🇦"},
		"LBP": {LBP, "🇱🇧"},
		"LKR": {LKR, "🇱🇰"},
		"LRD": {LRD, "🇱🇷"},
		"LSL": {LSL, "🇱🇸"},
		"LTL": {LTL, ""},
		"LVL": {LVL, ""},
		"LYD": {LYD, ""},
		"MAD": {MAD, "🇲🇦"},
		"MDL": {MDL, "🇲🇩"},
		"MGA": {MGA, "🇲🇬"},
		"MKD": {MKD, "🇲🇰"},
		"MMK": {MMK, "🇲🇲"},
		"MNT": {MNT, "🇲🇳"},
		"MOP": {MOP, "🇲🇴"},
		"MRO": {MRO, "🇲🇷"},
		"MUR": {MUR, "🇲🇺"},
		"MVR": {MVR, "🇲🇻"},
		"MWK": {MWK, "🇲🇼"},
		"MXN": {MXN, "🇲🇽"},
		"MXV": {MXV, ""},
		"MYR": {MYR, "🇲🇾"},
		"MZN": {MZN, "🇲🇿"},
		"NAD": {NAD, "🇳🇦"},
		"NGN": {NGN, "🇳🇬"},
		"NIO": {NIO, "🇳🇮"},
		"NOK": {NOK, "🇳🇴"},
		"NPR": {NPR, "🇳🇵"},
		"NZD": {NZD, "🇳🇿"},
		"OMR": {OMR, ""},
		"PAB": {PAB, "🇵🇦"},
		"PEN": {PEN, "🇵🇪"},
		"PGK": {PGK, "🇵🇬"},
		"PHP": {PHP, "🇵🇭"},
		"PKR": {PKR, "🇵🇰"},
		"PLN": {PLN, "🇵🇱"},
		"PYG": {PYG, "🇵🇾"},
		"QAR": {QAR, "🇶🇦"},
		"RON": {RON, "🇷🇴"},
		"RSD": {RSD, "🇷🇸"},
		"RUB": {RUB, "🇷🇺"},
		"RWF": {RWF, "🇷🇼"},
		"SAR": {SAR, "🇸🇦"},
		"SBD": {SBD, "🇸🇧"},
		"SCR": {SCR, "🇸🇨"},
		"SDG": {SDG, ""},
		"SEK": {SEK, "🇸🇪"},
		"SGD": {SGD, "🇸🇬"},
		"SHP": {SHP, "🇸🇭"},
		"SLL": {SLL, "🇸🇱"},
		"SOS": {SOS, "🇸🇴"},
		"SRD": {SRD, "🇸🇷"},
		"SSP": {SSP, ""},
		"STD": {STD, "🇸🇹"},
		"SYP": {SYP, ""},
		"SZL": {SZL, "🇸🇿"},
		"THB": {THB, "🇹🇭"},
		"TJS": {TJS, "🇹🇯"},
		"TMT": {TMT, ""},
		"TND": {TND, ""},
		"TOP": {TOP, "🇹🇴"},
		"TRY": {TRY, "🇹🇷"},
		"TTD": {TTD, "🇹🇹"},
		"TWD": {TWD, "🇹🇼"},
		"TZS": {TZS, "🇹🇿"},
		"UAH": {UAH, "🇺🇦"},
		"UGX": {UGX, "🇺🇬"},
		"USD": {USD, "🇺🇸"},
		"USN": {USN, ""},
		"USS": {USS, ""},
		"UYI": {UYI, ""},
		"UYU": {UYU, "🇺🇾"},
		"UZS": {UZS, "🇺🇿"},
		"VEF": {VEF, ""},
		"VND": {VND, "🇻🇳"},
		"VUV": {VUV, "🇻🇺"},
		"WST": {WST, "🇼🇸"},
		"XAF": {XAF, "🇨🇲"},
		"XAG": {XAG, ""},
		"XAU": {XAU, ""},
		"XBA": {XBA, ""},
		"XBB": {XBB, ""},
		"XBC": {XBC, ""},
		"XBD": {XBD, ""},
		"XCD": {XCD, "🇦🇮"},
		"XDR": {XDR, ""},
		"XFU": {XFU, ""},
		"XOF": {XOF, "🇧🇯"},
		"XPD": {XPD, ""},
		"XPF": {XPF, "🇵🇫"},
		"XPT": {XPT, ""},
		"XTS": {XTS, ""},
		"XXX": {XXX, ""},
		"YER": {YER, "🇾🇪"},
		"ZAR": {ZAR, "🇿🇦"},
		"ZMW": {ZMW, "🇿🇲"},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			if got := tc.code.Flag(); got != tc.want {
				t.Errorf("Flag() = %v, want %v", got, tc.want)
			}
		})
	}
}

func TestCurrencyCode_MarshalJSON(t *testing.T) {
	type tcase struct {
		code    CurrencyCode
		want    []byte
		wantErr error
	}

	tests := map[string]tcase{
		"ErrMarshalJSON": {0, nil, ErrMarshalJSON},
		"AED":            {AED, []byte(`"AED"`), nil},
		"AFN":            {AFN, []byte(`"AFN"`), nil},
		"ALL":            {ALL, []byte(`"ALL"`), nil},
		"AMD":            {AMD, []byte(`"AMD"`), nil},
		"ANG":            {ANG, []byte(`"ANG"`), nil},
		"AOA":            {AOA, []byte(`"AOA"`), nil},
		"ARS":            {ARS, []byte(`"ARS"`), nil},
		"AUD":            {AUD, []byte(`"AUD"`), nil},
		"AWG":            {AWG, []byte(`"AWG"`), nil},
		"AZN":            {AZN, []byte(`"AZN"`), nil},
		"BAM":            {BAM, []byte(`"BAM"`), nil},
		"BBD":            {BBD, []byte(`"BBD"`), nil},
		"BDT":            {BDT, []byte(`"BDT"`), nil},
		"BGN":            {BGN, []byte(`"BGN"`), nil},
		"BHD":            {BHD, []byte(`"BHD"`), nil},
		"BIF":            {BIF, []byte(`"BIF"`), nil},
		"BMD":            {BMD, []byte(`"BMD"`), nil},
		"BND":            {BND, []byte(`"BND"`), nil},
		"BOB":            {BOB, []byte(`"BOB"`), nil},
		"BOV":            {BOV, []byte(`"BOV"`), nil},
		"BRL":            {BRL, []byte(`"BRL"`), nil},
		"BSD":            {BSD, []byte(`"BSD"`), nil},
		"BTN":            {BTN, []byte(`"BTN"`), nil},
		"BWP":            {BWP, []byte(`"BWP"`), nil},
		"BYR":            {BYR, []byte(`"BYR"`), nil},
		"BZD":            {BZD, []byte(`"BZD"`), nil},
		"CAD":            {CAD, []byte(`"CAD"`), nil},
		"CDF":            {CDF, []byte(`"CDF"`), nil},
		"CHE":            {CHE, []byte(`"CHE"`), nil},
		"CHF":            {CHF, []byte(`"CHF"`), nil},
		"CHW":            {CHW, []byte(`"CHW"`), nil},
		"CLF":            {CLF, []byte(`"CLF"`), nil},
		"CLP":            {CLP, []byte(`"CLP"`), nil},
		"CNY":            {CNY, []byte(`"CNY"`), nil},
		"COP":            {COP, []byte(`"COP"`), nil},
		"COU":            {COU, []byte(`"COU"`), nil},
		"CRC":            {CRC, []byte(`"CRC"`), nil},
		"CUC":            {CUC, []byte(`"CUC"`), nil},
		"CUP":            {CUP, []byte(`"CUP"`), nil},
		"CVE":            {CVE, []byte(`"CVE"`), nil},
		"CZK":            {CZK, []byte(`"CZK"`), nil},
		"DJF":            {DJF, []byte(`"DJF"`), nil},
		"DKK":            {DKK, []byte(`"DKK"`), nil},
		"DOP":            {DOP, []byte(`"DOP"`), nil},
		"DZD":            {DZD, []byte(`"DZD"`), nil},
		"EGP":            {EGP, []byte(`"EGP"`), nil},
		"ERN":            {ERN, []byte(`"ERN"`), nil},
		"ETB":            {ETB, []byte(`"ETB"`), nil},
		"EUR":            {EUR, []byte(`"EUR"`), nil},
		"FJD":            {FJD, []byte(`"FJD"`), nil},
		"FKP":            {FKP, []byte(`"FKP"`), nil},
		"GBP":            {GBP, []byte(`"GBP"`), nil},
		"GEL":            {GEL, []byte(`"GEL"`), nil},
		"GHS":            {GHS, []byte(`"GHS"`), nil},
		"GIP":            {GIP, []byte(`"GIP"`), nil},
		"GMD":            {GMD, []byte(`"GMD"`), nil},
		"GNF":            {GNF, []byte(`"GNF"`), nil},
		"GTQ":            {GTQ, []byte(`"GTQ"`), nil},
		"GYD":            {GYD, []byte(`"GYD"`), nil},
		"HKD":            {HKD, []byte(`"HKD"`), nil},
		"HNL":            {HNL, []byte(`"HNL"`), nil},
		"HRK":            {HRK, []byte(`"HRK"`), nil},
		"HTG":            {HTG, []byte(`"HTG"`), nil},
		"HUF":            {HUF, []byte(`"HUF"`), nil},
		"IDR":            {IDR, []byte(`"IDR"`), nil},
		"ILS":            {ILS, []byte(`"ILS"`), nil},
		"INR":            {INR, []byte(`"INR"`), nil},
		"IQD":            {IQD, []byte(`"IQD"`), nil},
		"IRR":            {IRR, []byte(`"IRR"`), nil},
		"ISK":            {ISK, []byte(`"ISK"`), nil},
		"JMD":            {JMD, []byte(`"JMD"`), nil},
		"JOD":            {JOD, []byte(`"JOD"`), nil},
		"JPY":            {JPY, []byte(`"JPY"`), nil},
		"KES":            {KES, []byte(`"KES"`), nil},
		"KGS":            {KGS, []byte(`"KGS"`), nil},
		"KHR":            {KHR, []byte(`"KHR"`), nil},
		"KMF":            {KMF, []byte(`"KMF"`), nil},
		"KPW":            {KPW, []byte(`"KPW"`), nil},
		"KRW":            {KRW, []byte(`"KRW"`), nil},
		"KWD":            {KWD, []byte(`"KWD"`), nil},
		"KYD":            {KYD, []byte(`"KYD"`), nil},
		"KZT":            {KZT, []byte(`"KZT"`), nil},
		"LAK":            {LAK, []byte(`"LAK"`), nil},
		"LBP":            {LBP, []byte(`"LBP"`), nil},
		"LKR":            {LKR, []byte(`"LKR"`), nil},
		"LRD":            {LRD, []byte(`"LRD"`), nil},
		"LSL":            {LSL, []byte(`"LSL"`), nil},
		"LTL":            {LTL, []byte(`"LTL"`), nil},
		"LVL":            {LVL, []byte(`"LVL"`), nil},
		"LYD":            {LYD, []byte(`"LYD"`), nil},
		"MAD":            {MAD, []byte(`"MAD"`), nil},
		"MDL":            {MDL, []byte(`"MDL"`), nil},
		"MGA":            {MGA, []byte(`"MGA"`), nil},
		"MKD":            {MKD, []byte(`"MKD"`), nil},
		"MMK":            {MMK, []byte(`"MMK"`), nil},
		"MNT":            {MNT, []byte(`"MNT"`), nil},
		"MOP":            {MOP, []byte(`"MOP"`), nil},
		"MRO":            {MRO, []byte(`"MRO"`), nil},
		"MUR":            {MUR, []byte(`"MUR"`), nil},
		"MVR":            {MVR, []byte(`"MVR"`), nil},
		"MWK":            {MWK, []byte(`"MWK"`), nil},
		"MXN":            {MXN, []byte(`"MXN"`), nil},
		"MXV":            {MXV, []byte(`"MXV"`), nil},
		"MYR":            {MYR, []byte(`"MYR"`), nil},
		"MZN":            {MZN, []byte(`"MZN"`), nil},
		"NAD":            {NAD, []byte(`"NAD"`), nil},
		"NGN":            {NGN, []byte(`"NGN"`), nil},
		"NIO":            {NIO, []byte(`"NIO"`), nil},
		"NOK":            {NOK, []byte(`"NOK"`), nil},
		"NPR":            {NPR, []byte(`"NPR"`), nil},
		"NZD":            {NZD, []byte(`"NZD"`), nil},
		"OMR":            {OMR, []byte(`"OMR"`), nil},
		"PAB":            {PAB, []byte(`"PAB"`), nil},
		"PEN":            {PEN, []byte(`"PEN"`), nil},
		"PGK":            {PGK, []byte(`"PGK"`), nil},
		"PHP":            {PHP, []byte(`"PHP"`), nil},
		"PKR":            {PKR, []byte(`"PKR"`), nil},
		"PLN":            {PLN, []byte(`"PLN"`), nil},
		"PYG":            {PYG, []byte(`"PYG"`), nil},
		"QAR":            {QAR, []byte(`"QAR"`), nil},
		"RON":            {RON, []byte(`"RON"`), nil},
		"RSD":            {RSD, []byte(`"RSD"`), nil},
		"RUB":            {RUB, []byte(`"RUB"`), nil},
		"RWF":            {RWF, []byte(`"RWF"`), nil},
		"SAR":            {SAR, []byte(`"SAR"`), nil},
		"SBD":            {SBD, []byte(`"SBD"`), nil},
		"SCR":            {SCR, []byte(`"SCR"`), nil},
		"SDG":            {SDG, []byte(`"SDG"`), nil},
		"SEK":            {SEK, []byte(`"SEK"`), nil},
		"SGD":            {SGD, []byte(`"SGD"`), nil},
		"SHP":            {SHP, []byte(`"SHP"`), nil},
		"SLL":            {SLL, []byte(`"SLL"`), nil},
		"SOS":            {SOS, []byte(`"SOS"`), nil},
		"SRD":            {SRD, []byte(`"SRD"`), nil},
		"SSP":            {SSP, []byte(`"SSP"`), nil},
		"STD":            {STD, []byte(`"STD"`), nil},
		"SYP":            {SYP, []byte(`"SYP"`), nil},
		"SZL":            {SZL, []byte(`"SZL"`), nil},
		"THB":            {THB, []byte(`"THB"`), nil},
		"TJS":            {TJS, []byte(`"TJS"`), nil},
		"TMT":            {TMT, []byte(`"TMT"`), nil},
		"TND":            {TND, []byte(`"TND"`), nil},
		"TOP":            {TOP, []byte(`"TOP"`), nil},
		"TRY":            {TRY, []byte(`"TRY"`), nil},
		"TTD":            {TTD, []byte(`"TTD"`), nil},
		"TWD":            {TWD, []byte(`"TWD"`), nil},
		"TZS":            {TZS, []byte(`"TZS"`), nil},
		"UAH":            {UAH, []byte(`"UAH"`), nil},
		"UGX":            {UGX, []byte(`"UGX"`), nil},
		"USD":            {USD, []byte(`"USD"`), nil},
		"USN":            {USN, []byte(`"USN"`), nil},
		"USS":            {USS, []byte(`"USS"`), nil},
		"UYI":            {UYI, []byte(`"UYI"`), nil},
		"UYU":            {UYU, []byte(`"UYU"`), nil},
		"UZS":            {UZS, []byte(`"UZS"`), nil},
		"VEF":            {VEF, []byte(`"VEF"`), nil},
		"VND":            {VND, []byte(`"VND"`), nil},
		"VUV":            {VUV, []byte(`"VUV"`), nil},
		"WST":            {WST, []byte(`"WST"`), nil},
		"XAF":            {XAF, []byte(`"XAF"`), nil},
		"XAG":            {XAG, []byte(`"XAG"`), nil},
		"XAU":            {XAU, []byte(`"XAU"`), nil},
		"XBA":            {XBA, []byte(`"XBA"`), nil},
		"XBB":            {XBB, []byte(`"XBB"`), nil},
		"XBC":            {XBC, []byte(`"XBC"`), nil},
		"XBD":            {XBD, []byte(`"XBD"`), nil},
		"XCD":            {XCD, []byte(`"XCD"`), nil},
		"XDR":            {XDR, []byte(`"XDR"`), nil},
		"XFU":            {XFU, []byte(`"XFU"`), nil},
		"XOF":            {XOF, []byte(`"XOF"`), nil},
		"XPD":            {XPD, []byte(`"XPD"`), nil},
		"XPF":            {XPF, []byte(`"XPF"`), nil},
		"XPT":            {XPT, []byte(`"XPT"`), nil},
		"XTS":            {XTS, []byte(`"XTS"`), nil},
		"XXX":            {XXX, []byte(`"XXX"`), nil},
		"YER":            {YER, []byte(`"YER"`), nil},
		"ZAR":            {ZAR, []byte(`"ZAR"`), nil},
		"ZMW":            {ZMW, []byte(`"ZMW"`), nil},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			got, err := tc.code.MarshalJSON()
			if tc.wantErr != nil {
				if !reflect.DeepEqual(tc.wantErr, err) {
					t.Errorf("MarshalJSON() error = %v, wantErr %v", err, tc.wantErr)
				}
			} else {
				if !reflect.DeepEqual(got, tc.want) {
					t.Errorf("MarshalJSON() got = %v, want %v", got, tc.want)
				}
			}
		})
	}
}

func TestCurrencyCode_MarshalText(t *testing.T) {
	type tcase struct {
		code    CurrencyCode
		want    []byte
		wantErr error
	}

	tests := map[string]tcase{
		"AED": {AED, []byte(`"AED"`), nil},
		"AFN": {AFN, []byte(`"AFN"`), nil},
		"ALL": {ALL, []byte(`"ALL"`), nil},
		"AMD": {AMD, []byte(`"AMD"`), nil},
		"ANG": {ANG, []byte(`"ANG"`), nil},
		"AOA": {AOA, []byte(`"AOA"`), nil},
		"ARS": {ARS, []byte(`"ARS"`), nil},
		"AUD": {AUD, []byte(`"AUD"`), nil},
		"AWG": {AWG, []byte(`"AWG"`), nil},
		"AZN": {AZN, []byte(`"AZN"`), nil},
		"BAM": {BAM, []byte(`"BAM"`), nil},
		"BBD": {BBD, []byte(`"BBD"`), nil},
		"BDT": {BDT, []byte(`"BDT"`), nil},
		"BGN": {BGN, []byte(`"BGN"`), nil},
		"BHD": {BHD, []byte(`"BHD"`), nil},
		"BIF": {BIF, []byte(`"BIF"`), nil},
		"BMD": {BMD, []byte(`"BMD"`), nil},
		"BND": {BND, []byte(`"BND"`), nil},
		"BOB": {BOB, []byte(`"BOB"`), nil},
		"BOV": {BOV, []byte(`"BOV"`), nil},
		"BRL": {BRL, []byte(`"BRL"`), nil},
		"BSD": {BSD, []byte(`"BSD"`), nil},
		"BTN": {BTN, []byte(`"BTN"`), nil},
		"BWP": {BWP, []byte(`"BWP"`), nil},
		"BYR": {BYR, []byte(`"BYR"`), nil},
		"BZD": {BZD, []byte(`"BZD"`), nil},
		"CAD": {CAD, []byte(`"CAD"`), nil},
		"CDF": {CDF, []byte(`"CDF"`), nil},
		"CHE": {CHE, []byte(`"CHE"`), nil},
		"CHF": {CHF, []byte(`"CHF"`), nil},
		"CHW": {CHW, []byte(`"CHW"`), nil},
		"CLF": {CLF, []byte(`"CLF"`), nil},
		"CLP": {CLP, []byte(`"CLP"`), nil},
		"CNY": {CNY, []byte(`"CNY"`), nil},
		"COP": {COP, []byte(`"COP"`), nil},
		"COU": {COU, []byte(`"COU"`), nil},
		"CRC": {CRC, []byte(`"CRC"`), nil},
		"CUC": {CUC, []byte(`"CUC"`), nil},
		"CUP": {CUP, []byte(`"CUP"`), nil},
		"CVE": {CVE, []byte(`"CVE"`), nil},
		"CZK": {CZK, []byte(`"CZK"`), nil},
		"DJF": {DJF, []byte(`"DJF"`), nil},
		"DKK": {DKK, []byte(`"DKK"`), nil},
		"DOP": {DOP, []byte(`"DOP"`), nil},
		"DZD": {DZD, []byte(`"DZD"`), nil},
		"EGP": {EGP, []byte(`"EGP"`), nil},
		"ERN": {ERN, []byte(`"ERN"`), nil},
		"ETB": {ETB, []byte(`"ETB"`), nil},
		"EUR": {EUR, []byte(`"EUR"`), nil},
		"FJD": {FJD, []byte(`"FJD"`), nil},
		"FKP": {FKP, []byte(`"FKP"`), nil},
		"GBP": {GBP, []byte(`"GBP"`), nil},
		"GEL": {GEL, []byte(`"GEL"`), nil},
		"GHS": {GHS, []byte(`"GHS"`), nil},
		"GIP": {GIP, []byte(`"GIP"`), nil},
		"GMD": {GMD, []byte(`"GMD"`), nil},
		"GNF": {GNF, []byte(`"GNF"`), nil},
		"GTQ": {GTQ, []byte(`"GTQ"`), nil},
		"GYD": {GYD, []byte(`"GYD"`), nil},
		"HKD": {HKD, []byte(`"HKD"`), nil},
		"HNL": {HNL, []byte(`"HNL"`), nil},
		"HRK": {HRK, []byte(`"HRK"`), nil},
		"HTG": {HTG, []byte(`"HTG"`), nil},
		"HUF": {HUF, []byte(`"HUF"`), nil},
		"IDR": {IDR, []byte(`"IDR"`), nil},
		"ILS": {ILS, []byte(`"ILS"`), nil},
		"INR": {INR, []byte(`"INR"`), nil},
		"IQD": {IQD, []byte(`"IQD"`), nil},
		"IRR": {IRR, []byte(`"IRR"`), nil},
		"ISK": {ISK, []byte(`"ISK"`), nil},
		"JMD": {JMD, []byte(`"JMD"`), nil},
		"JOD": {JOD, []byte(`"JOD"`), nil},
		"JPY": {JPY, []byte(`"JPY"`), nil},
		"KES": {KES, []byte(`"KES"`), nil},
		"KGS": {KGS, []byte(`"KGS"`), nil},
		"KHR": {KHR, []byte(`"KHR"`), nil},
		"KMF": {KMF, []byte(`"KMF"`), nil},
		"KPW": {KPW, []byte(`"KPW"`), nil},
		"KRW": {KRW, []byte(`"KRW"`), nil},
		"KWD": {KWD, []byte(`"KWD"`), nil},
		"KYD": {KYD, []byte(`"KYD"`), nil},
		"KZT": {KZT, []byte(`"KZT"`), nil},
		"LAK": {LAK, []byte(`"LAK"`), nil},
		"LBP": {LBP, []byte(`"LBP"`), nil},
		"LKR": {LKR, []byte(`"LKR"`), nil},
		"LRD": {LRD, []byte(`"LRD"`), nil},
		"LSL": {LSL, []byte(`"LSL"`), nil},
		"LTL": {LTL, []byte(`"LTL"`), nil},
		"LVL": {LVL, []byte(`"LVL"`), nil},
		"LYD": {LYD, []byte(`"LYD"`), nil},
		"MAD": {MAD, []byte(`"MAD"`), nil},
		"MDL": {MDL, []byte(`"MDL"`), nil},
		"MGA": {MGA, []byte(`"MGA"`), nil},
		"MKD": {MKD, []byte(`"MKD"`), nil},
		"MMK": {MMK, []byte(`"MMK"`), nil},
		"MNT": {MNT, []byte(`"MNT"`), nil},
		"MOP": {MOP, []byte(`"MOP"`), nil},
		"MRO": {MRO, []byte(`"MRO"`), nil},
		"MUR": {MUR, []byte(`"MUR"`), nil},
		"MVR": {MVR, []byte(`"MVR"`), nil},
		"MWK": {MWK, []byte(`"MWK"`), nil},
		"MXN": {MXN, []byte(`"MXN"`), nil},
		"MXV": {MXV, []byte(`"MXV"`), nil},
		"MYR": {MYR, []byte(`"MYR"`), nil},
		"MZN": {MZN, []byte(`"MZN"`), nil},
		"NAD": {NAD, []byte(`"NAD"`), nil},
		"NGN": {NGN, []byte(`"NGN"`), nil},
		"NIO": {NIO, []byte(`"NIO"`), nil},
		"NOK": {NOK, []byte(`"NOK"`), nil},
		"NPR": {NPR, []byte(`"NPR"`), nil},
		"NZD": {NZD, []byte(`"NZD"`), nil},
		"OMR": {OMR, []byte(`"OMR"`), nil},
		"PAB": {PAB, []byte(`"PAB"`), nil},
		"PEN": {PEN, []byte(`"PEN"`), nil},
		"PGK": {PGK, []byte(`"PGK"`), nil},
		"PHP": {PHP, []byte(`"PHP"`), nil},
		"PKR": {PKR, []byte(`"PKR"`), nil},
		"PLN": {PLN, []byte(`"PLN"`), nil},
		"PYG": {PYG, []byte(`"PYG"`), nil},
		"QAR": {QAR, []byte(`"QAR"`), nil},
		"RON": {RON, []byte(`"RON"`), nil},
		"RSD": {RSD, []byte(`"RSD"`), nil},
		"RUB": {RUB, []byte(`"RUB"`), nil},
		"RWF": {RWF, []byte(`"RWF"`), nil},
		"SAR": {SAR, []byte(`"SAR"`), nil},
		"SBD": {SBD, []byte(`"SBD"`), nil},
		"SCR": {SCR, []byte(`"SCR"`), nil},
		"SDG": {SDG, []byte(`"SDG"`), nil},
		"SEK": {SEK, []byte(`"SEK"`), nil},
		"SGD": {SGD, []byte(`"SGD"`), nil},
		"SHP": {SHP, []byte(`"SHP"`), nil},
		"SLL": {SLL, []byte(`"SLL"`), nil},
		"SOS": {SOS, []byte(`"SOS"`), nil},
		"SRD": {SRD, []byte(`"SRD"`), nil},
		"SSP": {SSP, []byte(`"SSP"`), nil},
		"STD": {STD, []byte(`"STD"`), nil},
		"SYP": {SYP, []byte(`"SYP"`), nil},
		"SZL": {SZL, []byte(`"SZL"`), nil},
		"THB": {THB, []byte(`"THB"`), nil},
		"TJS": {TJS, []byte(`"TJS"`), nil},
		"TMT": {TMT, []byte(`"TMT"`), nil},
		"TND": {TND, []byte(`"TND"`), nil},
		"TOP": {TOP, []byte(`"TOP"`), nil},
		"TRY": {TRY, []byte(`"TRY"`), nil},
		"TTD": {TTD, []byte(`"TTD"`), nil},
		"TWD": {TWD, []byte(`"TWD"`), nil},
		"TZS": {TZS, []byte(`"TZS"`), nil},
		"UAH": {UAH, []byte(`"UAH"`), nil},
		"UGX": {UGX, []byte(`"UGX"`), nil},
		"USD": {USD, []byte(`"USD"`), nil},
		"USN": {USN, []byte(`"USN"`), nil},
		"USS": {USS, []byte(`"USS"`), nil},
		"UYI": {UYI, []byte(`"UYI"`), nil},
		"UYU": {UYU, []byte(`"UYU"`), nil},
		"UZS": {UZS, []byte(`"UZS"`), nil},
		"VEF": {VEF, []byte(`"VEF"`), nil},
		"VND": {VND, []byte(`"VND"`), nil},
		"VUV": {VUV, []byte(`"VUV"`), nil},
		"WST": {WST, []byte(`"WST"`), nil},
		"XAF": {XAF, []byte(`"XAF"`), nil},
		"XAG": {XAG, []byte(`"XAG"`), nil},
		"XAU": {XAU, []byte(`"XAU"`), nil},
		"XBA": {XBA, []byte(`"XBA"`), nil},
		"XBB": {XBB, []byte(`"XBB"`), nil},
		"XBC": {XBC, []byte(`"XBC"`), nil},
		"XBD": {XBD, []byte(`"XBD"`), nil},
		"XCD": {XCD, []byte(`"XCD"`), nil},
		"XDR": {XDR, []byte(`"XDR"`), nil},
		"XFU": {XFU, []byte(`"XFU"`), nil},
		"XOF": {XOF, []byte(`"XOF"`), nil},
		"XPD": {XPD, []byte(`"XPD"`), nil},
		"XPF": {XPF, []byte(`"XPF"`), nil},
		"XPT": {XPT, []byte(`"XPT"`), nil},
		"XTS": {XTS, []byte(`"XTS"`), nil},
		"XXX": {XXX, []byte(`"XXX"`), nil},
		"YER": {YER, []byte(`"YER"`), nil},
		"ZAR": {ZAR, []byte(`"ZAR"`), nil},
		"ZMW": {ZMW, []byte(`"ZMW"`), nil},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			got, err := tc.code.MarshalText()
			if tc.wantErr != nil {
				if !reflect.DeepEqual(tc.wantErr, err) {
					t.Errorf("MarshalText() error = %v, wantErr %v", err, tc.wantErr)
				}
			} else {
				if !reflect.DeepEqual(got, tc.want) {
					t.Errorf("MarshalText() got = %v, want %v", got, tc.want)
				}
			}
		})
	}
}

func TestCurrencyCode_Name(t *testing.T) {
	type tcase struct {
		code CurrencyCode
		want string
	}

	tests := map[string]tcase{
		"AED": {AED, "United Arab Emirates dirham"},
		"AFN": {AFN, "Afghan afghani"},
		"ALL": {ALL, "Albanian lek"},
		"AMD": {AMD, "Armenian dram"},
		"ANG": {ANG, "Netherlands Antillean guilder"},
		"AOA": {AOA, "Angolan kwanza"},
		"ARS": {ARS, "Argentine peso"},
		"AUD": {AUD, "Australian dollar"},
		"AWG": {AWG, "Aruban florin"},
		"AZN": {AZN, "Azerbaijani manat"},
		"BAM": {BAM, "Bosnia and Herzegovina convertible mark"},
		"BBD": {BBD, "Barbados dollar"},
		"BDT": {BDT, "Bangladeshi taka"},
		"BGN": {BGN, "Bulgarian lev"},
		"BHD": {BHD, "Bahraini dinar"},
		"BIF": {BIF, "Burundian franc"},
		"BMD": {BMD, "Bermudian dollar (customarily known as Bermuda dollar)"},
		"BND": {BND, "Brunei dollar"},
		"BOB": {BOB, "Boliviano"},
		"BOV": {BOV, "Bolivian Mvdol (funds code)"},
		"BRL": {BRL, "Brazilian real"},
		"BSD": {BSD, "Bahamian dollar"},
		"BTN": {BTN, "Bhutanese ngultrum"},
		"BWP": {BWP, "Botswana pula"},
		"BYR": {BYR, "Belarusian ruble"},
		"BZD": {BZD, "Belize dollar"},
		"CAD": {CAD, "Canadian dollar"},
		"CDF": {CDF, "Congolese franc"},
		"CHE": {CHE, "WIR Euro (complementary currency)"},
		"CHF": {CHF, "Swiss franc"},
		"CHW": {CHW, "WIR Franc (complementary currency)"},
		"CLF": {CLF, "Unidad de Fomento (funds code)"},
		"CLP": {CLP, "Chilean peso"},
		"CNY": {CNY, "Chinese yuan"},
		"COP": {COP, "Colombian peso"},
		"COU": {COU, "Unidad de Valor Real"},
		"CRC": {CRC, "Costa Rican colon"},
		"CUC": {CUC, "Cuban convertible peso"},
		"CUP": {CUP, "Cuban peso"},
		"CVE": {CVE, "Cape Verde escudo"},
		"CZK": {CZK, "Czech koruna"},
		"DJF": {DJF, "Djiboutian franc"},
		"DKK": {DKK, "Danish krone"},
		"DOP": {DOP, "Dominican peso"},
		"DZD": {DZD, "Algerian dinar"},
		"EGP": {EGP, "Egyptian pound"},
		"ERN": {ERN, "Eritrean nakfa"},
		"ETB": {ETB, "Ethiopian birr"},
		"EUR": {EUR, "Euro"},
		"FJD": {FJD, "Fiji dollar"},
		"FKP": {FKP, "Falkland Islands pound"},
		"GBP": {GBP, "Pound sterling"},
		"GEL": {GEL, "Georgian lari"},
		"GHS": {GHS, "Ghanaian cedi"},
		"GIP": {GIP, "Gibraltar pound"},
		"GMD": {GMD, "Gambian dalasi"},
		"GNF": {GNF, "Guinean franc"},
		"GTQ": {GTQ, "Guatemalan quetzal"},
		"GYD": {GYD, "Guyanese dollar"},
		"HKD": {HKD, "Hong Kong dollar"},
		"HNL": {HNL, "Honduran lempira"},
		"HRK": {HRK, "Croatian kuna"},
		"HTG": {HTG, "Haitian gourde"},
		"HUF": {HUF, "Hungarian forint"},
		"IDR": {IDR, "Indonesian rupiah"},
		"ILS": {ILS, "Israeli new shekel"},
		"INR": {INR, "Indian rupee"},
		"IQD": {IQD, "Iraqi dinar"},
		"IRR": {IRR, "Iranian rial"},
		"ISK": {ISK, "Icelandic króna"},
		"JMD": {JMD, "Jamaican dollar"},
		"JOD": {JOD, "Jordanian dinar"},
		"JPY": {JPY, "Japanese yen"},
		"KES": {KES, "Kenyan shilling"},
		"KGS": {KGS, "Kyrgyzstani som"},
		"KHR": {KHR, "Cambodian riel"},
		"KMF": {KMF, "Comoro franc"},
		"KPW": {KPW, "North Korean won"},
		"KRW": {KRW, "South Korean won"},
		"KWD": {KWD, "Kuwaiti dinar"},
		"KYD": {KYD, "Cayman Islands dollar"},
		"KZT": {KZT, "Kazakhstani tenge"},
		"LAK": {LAK, "Lao kip"},
		"LBP": {LBP, "Lebanese pound"},
		"LKR": {LKR, "Sri Lankan rupee"},
		"LRD": {LRD, "Liberian dollar"},
		"LSL": {LSL, "Lesotho loti"},
		"LTL": {LTL, "Lithuanian litas"},
		"LVL": {LVL, "Latvian lats"},
		"LYD": {LYD, "Libyan dinar"},
		"MAD": {MAD, "Moroccan dirham"},
		"MDL": {MDL, "Moldovan leu"},
		"MGA": {MGA, "Malagasy ariary"},
		"MKD": {MKD, "Macedonian denar"},
		"MMK": {MMK, "Myanma kyat"},
		"MNT": {MNT, "Mongolian tugrik"},
		"MOP": {MOP, "Macanese pataca"},
		"MRO": {MRO, "Mauritanian ouguiya"},
		"MUR": {MUR, "Mauritian rupee"},
		"MVR": {MVR, "Maldivian rufiyaa"},
		"MWK": {MWK, "Malawian kwacha"},
		"MXN": {MXN, "Mexican peso"},
		"MXV": {MXV, "Mexican Unidad de Inversion (UDI) (funds code)"},
		"MYR": {MYR, "Malaysian ringgit"},
		"MZN": {MZN, "Mozambican metical"},
		"NAD": {NAD, "Namibian dollar"},
		"NGN": {NGN, "Nigerian naira"},
		"NIO": {NIO, "Nicaraguan córdoba"},
		"NOK": {NOK, "Norwegian krone"},
		"NPR": {NPR, "Nepalese rupee"},
		"NZD": {NZD, "New Zealand dollar"},
		"OMR": {OMR, "Omani rial"},
		"PAB": {PAB, "Panamanian balboa"},
		"PEN": {PEN, "Peruvian nuevo sol"},
		"PGK": {PGK, "Papua New Guinean kina"},
		"PHP": {PHP, "Philippine peso"},
		"PKR": {PKR, "Pakistani rupee"},
		"PLN": {PLN, "Polish złoty"},
		"PYG": {PYG, "Paraguayan guaraní"},
		"QAR": {QAR, "Qatari riyal"},
		"RON": {RON, "Romanian new leu"},
		"RSD": {RSD, "Serbian dinar"},
		"RUB": {RUB, "Russian rouble"},
		"RWF": {RWF, "Rwandan franc"},
		"SAR": {SAR, "Saudi riyal"},
		"SBD": {SBD, "Solomon Islands dollar"},
		"SCR": {SCR, "Seychelles rupee"},
		"SDG": {SDG, "Sudanese pound"},
		"SEK": {SEK, "Swedish krona/kronor"},
		"SGD": {SGD, "Singapore dollar"},
		"SHP": {SHP, "Saint Helena pound"},
		"SLL": {SLL, "Sierra Leonean leone"},
		"SOS": {SOS, "Somali shilling"},
		"SRD": {SRD, "Surinamese dollar"},
		"SSP": {SSP, "South Sudanese pound"},
		"STD": {STD, "São Tomé and Príncipe dobra"},
		"SYP": {SYP, "Syrian pound"},
		"SZL": {SZL, "Swazi lilangeni"},
		"THB": {THB, "Thai baht"},
		"TJS": {TJS, "Tajikistani somoni"},
		"TMT": {TMT, "Turkmenistani manat"},
		"TND": {TND, "Tunisian dinar"},
		"TOP": {TOP, "Tongan paʻanga"},
		"TRY": {TRY, "Turkish lira"},
		"TTD": {TTD, "Trinidad and Tobago dollar"},
		"TWD": {TWD, "New Taiwan dollar"},
		"TZS": {TZS, "Tanzanian shilling"},
		"UAH": {UAH, "Ukrainian hryvnia"},
		"UGX": {UGX, "Ugandan shilling"},
		"USD": {USD, "United States dollar"},
		"USN": {USN, "United States dollar (next day) (funds code)"},
		"USS": {USS, "United States dollar (same day) (funds code)"},
		"UYI": {UYI, "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)"},
		"UYU": {UYU, "Uruguayan peso"},
		"UZS": {UZS, "Uzbekistan som"},
		"VEF": {VEF, "Venezuelan bolívar fuerte"},
		"VND": {VND, "Vietnamese dong"},
		"VUV": {VUV, "Vanuatu vatu"},
		"WST": {WST, "Samoan tala"},
		"XAF": {XAF, "CFA franc BEAC"},
		"XAG": {XAG, "Silver (one troy ounce)"},
		"XAU": {XAU, "Gold (one troy ounce)"},
		"XBA": {XBA, "European Composite Unit (EURCO) (bond market unit)"},
		"XBB": {XBB, "European Monetary Unit (E.M.U.-6) (bond market unit)"},
		"XBC": {XBC, "European Unit of Account 9 (E.U.A.-9) (bond market unit)"},
		"XBD": {XBD, "European Unit of Account 17 (E.U.A.-17) (bond market unit)"},
		"XCD": {XCD, "East Caribbean dollar"},
		"XDR": {XDR, "Special drawing rights"},
		"XFU": {XFU, "UIC franc (special settlement currency)"},
		"XOF": {XOF, "CFA franc BCEAO"},
		"XPD": {XPD, "Palladium (one troy ounce)"},
		"XPF": {XPF, "CFP franc"},
		"XPT": {XPT, "Platinum (one troy ounce)"},
		"XTS": {XTS, "Code reserved for testing purposes"},
		"XXX": {XXX, "No currency"},
		"YER": {YER, "Yemeni rial"},
		"ZAR": {ZAR, "South African rand"},
		"ZMW": {ZMW, "Zambian kwacha"},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			if got := tc.code.Name(); got != tc.want {
				t.Errorf("Name() = %v, want %v", got, tc.want)
			}
		})
	}
}

func TestCurrencyCode_Number(t *testing.T) {
	type tcase struct {
		code CurrencyCode
		want string
	}

	tests := map[string]tcase{
		"AED": {AED, "784"},
		"AFN": {AFN, "971"},
		"ALL": {ALL, "8"},
		"AMD": {AMD, "51"},
		"ANG": {ANG, "532"},
		"AOA": {AOA, "973"},
		"ARS": {ARS, "32"},
		"AUD": {AUD, "36"},
		"AWG": {AWG, "533"},
		"AZN": {AZN, "944"},
		"BAM": {BAM, "977"},
		"BBD": {BBD, "52"},
		"BDT": {BDT, "50"},
		"BGN": {BGN, "975"},
		"BHD": {BHD, "48"},
		"BIF": {BIF, "108"},
		"BMD": {BMD, "60"},
		"BND": {BND, "96"},
		"BOB": {BOB, "68"},
		"BOV": {BOV, "984"},
		"BRL": {BRL, "986"},
		"BSD": {BSD, "44"},
		"BTN": {BTN, "64"},
		"BWP": {BWP, "72"},
		"BYR": {BYR, "974"},
		"BZD": {BZD, "84"},
		"CAD": {CAD, "124"},
		"CDF": {CDF, "976"},
		"CHE": {CHE, "947"},
		"CHF": {CHF, "756"},
		"CHW": {CHW, "948"},
		"CLF": {CLF, "990"},
		"CLP": {CLP, "152"},
		"CNY": {CNY, "156"},
		"COP": {COP, "170"},
		"COU": {COU, "970"},
		"CRC": {CRC, "188"},
		"CUC": {CUC, "931"},
		"CUP": {CUP, "192"},
		"CVE": {CVE, "132"},
		"CZK": {CZK, "203"},
		"DJF": {DJF, "262"},
		"DKK": {DKK, "208"},
		"DOP": {DOP, "214"},
		"DZD": {DZD, "12"},
		"EGP": {EGP, "818"},
		"ERN": {ERN, "232"},
		"ETB": {ETB, "230"},
		"EUR": {EUR, "978"},
		"FJD": {FJD, "242"},
		"FKP": {FKP, "238"},
		"GBP": {GBP, "826"},
		"GEL": {GEL, "981"},
		"GHS": {GHS, "936"},
		"GIP": {GIP, "292"},
		"GMD": {GMD, "270"},
		"GNF": {GNF, "324"},
		"GTQ": {GTQ, "320"},
		"GYD": {GYD, "328"},
		"HKD": {HKD, "344"},
		"HNL": {HNL, "340"},
		"HRK": {HRK, "191"},
		"HTG": {HTG, "332"},
		"HUF": {HUF, "348"},
		"IDR": {IDR, "360"},
		"ILS": {ILS, "376"},
		"INR": {INR, "356"},
		"IQD": {IQD, "368"},
		"IRR": {IRR, "364"},
		"ISK": {ISK, "352"},
		"JMD": {JMD, "388"},
		"JOD": {JOD, "400"},
		"JPY": {JPY, "392"},
		"KES": {KES, "404"},
		"KGS": {KGS, "417"},
		"KHR": {KHR, "116"},
		"KMF": {KMF, "174"},
		"KPW": {KPW, "408"},
		"KRW": {KRW, "410"},
		"KWD": {KWD, "414"},
		"KYD": {KYD, "136"},
		"KZT": {KZT, "398"},
		"LAK": {LAK, "418"},
		"LBP": {LBP, "422"},
		"LKR": {LKR, "144"},
		"LRD": {LRD, "430"},
		"LSL": {LSL, "426"},
		"LTL": {LTL, "440"},
		"LVL": {LVL, "428"},
		"LYD": {LYD, "434"},
		"MAD": {MAD, "504"},
		"MDL": {MDL, "498"},
		"MGA": {MGA, "969"},
		"MKD": {MKD, "807"},
		"MMK": {MMK, "104"},
		"MNT": {MNT, "496"},
		"MOP": {MOP, "446"},
		"MRO": {MRO, "478"},
		"MUR": {MUR, "480"},
		"MVR": {MVR, "462"},
		"MWK": {MWK, "454"},
		"MXN": {MXN, "484"},
		"MXV": {MXV, "979"},
		"MYR": {MYR, "458"},
		"MZN": {MZN, "943"},
		"NAD": {NAD, "516"},
		"NGN": {NGN, "566"},
		"NIO": {NIO, "558"},
		"NOK": {NOK, "578"},
		"NPR": {NPR, "524"},
		"NZD": {NZD, "554"},
		"OMR": {OMR, "512"},
		"PAB": {PAB, "590"},
		"PEN": {PEN, "604"},
		"PGK": {PGK, "598"},
		"PHP": {PHP, "608"},
		"PKR": {PKR, "586"},
		"PLN": {PLN, "985"},
		"PYG": {PYG, "600"},
		"QAR": {QAR, "634"},
		"RON": {RON, "946"},
		"RSD": {RSD, "941"},
		"RUB": {RUB, "643"},
		"RWF": {RWF, "646"},
		"SAR": {SAR, "682"},
		"SBD": {SBD, "90"},
		"SCR": {SCR, "690"},
		"SDG": {SDG, "938"},
		"SEK": {SEK, "752"},
		"SGD": {SGD, "702"},
		"SHP": {SHP, "654"},
		"SLL": {SLL, "694"},
		"SOS": {SOS, "706"},
		"SRD": {SRD, "968"},
		"SSP": {SSP, "728"},
		"STD": {STD, "678"},
		"SYP": {SYP, "760"},
		"SZL": {SZL, "748"},
		"THB": {THB, "764"},
		"TJS": {TJS, "972"},
		"TMT": {TMT, "934"},
		"TND": {TND, "788"},
		"TOP": {TOP, "776"},
		"TRY": {TRY, "949"},
		"TTD": {TTD, "780"},
		"TWD": {TWD, "901"},
		"TZS": {TZS, "834"},
		"UAH": {UAH, "980"},
		"UGX": {UGX, "800"},
		"USD": {USD, "840"},
		"USN": {USN, "997"},
		"USS": {USS, "998"},
		"UYI": {UYI, "940"},
		"UYU": {UYU, "858"},
		"UZS": {UZS, "860"},
		"VEF": {VEF, "937"},
		"VND": {VND, "704"},
		"VUV": {VUV, "548"},
		"WST": {WST, "882"},
		"XAF": {XAF, "950"},
		"XAG": {XAG, "961"},
		"XAU": {XAU, "959"},
		"XBA": {XBA, "955"},
		"XBB": {XBB, "956"},
		"XBC": {XBC, "957"},
		"XBD": {XBD, "958"},
		"XCD": {XCD, "951"},
		"XDR": {XDR, "960"},
		"XFU": {XFU, "Nil"},
		"XOF": {XOF, "952"},
		"XPD": {XPD, "964"},
		"XPF": {XPF, "953"},
		"XPT": {XPT, "962"},
		"XTS": {XTS, "963"},
		"XXX": {XXX, "999"},
		"YER": {YER, "886"},
		"ZAR": {ZAR, "710"},
		"ZMW": {ZMW, "967"},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			if got := tc.code.Number(); got != tc.want {
				t.Errorf("Number() = %v, want %v", got, tc.want)
			}
		})
	}
}

func TestCurrencyCode_String(t *testing.T) {
	type tcase struct {
		code CurrencyCode
		want string
	}

	tests := map[string]tcase{
		"AED": {AED, "AED"},
		"AFN": {AFN, "AFN"},
		"ALL": {ALL, "ALL"},
		"AMD": {AMD, "AMD"},
		"ANG": {ANG, "ANG"},
		"AOA": {AOA, "AOA"},
		"ARS": {ARS, "ARS"},
		"AUD": {AUD, "AUD"},
		"AWG": {AWG, "AWG"},
		"AZN": {AZN, "AZN"},
		"BAM": {BAM, "BAM"},
		"BBD": {BBD, "BBD"},
		"BDT": {BDT, "BDT"},
		"BGN": {BGN, "BGN"},
		"BHD": {BHD, "BHD"},
		"BIF": {BIF, "BIF"},
		"BMD": {BMD, "BMD"},
		"BND": {BND, "BND"},
		"BOB": {BOB, "BOB"},
		"BOV": {BOV, "BOV"},
		"BRL": {BRL, "BRL"},
		"BSD": {BSD, "BSD"},
		"BTN": {BTN, "BTN"},
		"BWP": {BWP, "BWP"},
		"BYR": {BYR, "BYR"},
		"BZD": {BZD, "BZD"},
		"CAD": {CAD, "CAD"},
		"CDF": {CDF, "CDF"},
		"CHE": {CHE, "CHE"},
		"CHF": {CHF, "CHF"},
		"CHW": {CHW, "CHW"},
		"CLF": {CLF, "CLF"},
		"CLP": {CLP, "CLP"},
		"CNY": {CNY, "CNY"},
		"COP": {COP, "COP"},
		"COU": {COU, "COU"},
		"CRC": {CRC, "CRC"},
		"CUC": {CUC, "CUC"},
		"CUP": {CUP, "CUP"},
		"CVE": {CVE, "CVE"},
		"CZK": {CZK, "CZK"},
		"DJF": {DJF, "DJF"},
		"DKK": {DKK, "DKK"},
		"DOP": {DOP, "DOP"},
		"DZD": {DZD, "DZD"},
		"EGP": {EGP, "EGP"},
		"ERN": {ERN, "ERN"},
		"ETB": {ETB, "ETB"},
		"EUR": {EUR, "EUR"},
		"FJD": {FJD, "FJD"},
		"FKP": {FKP, "FKP"},
		"GBP": {GBP, "GBP"},
		"GEL": {GEL, "GEL"},
		"GHS": {GHS, "GHS"},
		"GIP": {GIP, "GIP"},
		"GMD": {GMD, "GMD"},
		"GNF": {GNF, "GNF"},
		"GTQ": {GTQ, "GTQ"},
		"GYD": {GYD, "GYD"},
		"HKD": {HKD, "HKD"},
		"HNL": {HNL, "HNL"},
		"HRK": {HRK, "HRK"},
		"HTG": {HTG, "HTG"},
		"HUF": {HUF, "HUF"},
		"IDR": {IDR, "IDR"},
		"ILS": {ILS, "ILS"},
		"INR": {INR, "INR"},
		"IQD": {IQD, "IQD"},
		"IRR": {IRR, "IRR"},
		"ISK": {ISK, "ISK"},
		"JMD": {JMD, "JMD"},
		"JOD": {JOD, "JOD"},
		"JPY": {JPY, "JPY"},
		"KES": {KES, "KES"},
		"KGS": {KGS, "KGS"},
		"KHR": {KHR, "KHR"},
		"KMF": {KMF, "KMF"},
		"KPW": {KPW, "KPW"},
		"KRW": {KRW, "KRW"},
		"KWD": {KWD, "KWD"},
		"KYD": {KYD, "KYD"},
		"KZT": {KZT, "KZT"},
		"LAK": {LAK, "LAK"},
		"LBP": {LBP, "LBP"},
		"LKR": {LKR, "LKR"},
		"LRD": {LRD, "LRD"},
		"LSL": {LSL, "LSL"},
		"LTL": {LTL, "LTL"},
		"LVL": {LVL, "LVL"},
		"LYD": {LYD, "LYD"},
		"MAD": {MAD, "MAD"},
		"MDL": {MDL, "MDL"},
		"MGA": {MGA, "MGA"},
		"MKD": {MKD, "MKD"},
		"MMK": {MMK, "MMK"},
		"MNT": {MNT, "MNT"},
		"MOP": {MOP, "MOP"},
		"MRO": {MRO, "MRO"},
		"MUR": {MUR, "MUR"},
		"MVR": {MVR, "MVR"},
		"MWK": {MWK, "MWK"},
		"MXN": {MXN, "MXN"},
		"MXV": {MXV, "MXV"},
		"MYR": {MYR, "MYR"},
		"MZN": {MZN, "MZN"},
		"NAD": {NAD, "NAD"},
		"NGN": {NGN, "NGN"},
		"NIO": {NIO, "NIO"},
		"NOK": {NOK, "NOK"},
		"NPR": {NPR, "NPR"},
		"NZD": {NZD, "NZD"},
		"OMR": {OMR, "OMR"},
		"PAB": {PAB, "PAB"},
		"PEN": {PEN, "PEN"},
		"PGK": {PGK, "PGK"},
		"PHP": {PHP, "PHP"},
		"PKR": {PKR, "PKR"},
		"PLN": {PLN, "PLN"},
		"PYG": {PYG, "PYG"},
		"QAR": {QAR, "QAR"},
		"RON": {RON, "RON"},
		"RSD": {RSD, "RSD"},
		"RUB": {RUB, "RUB"},
		"RWF": {RWF, "RWF"},
		"SAR": {SAR, "SAR"},
		"SBD": {SBD, "SBD"},
		"SCR": {SCR, "SCR"},
		"SDG": {SDG, "SDG"},
		"SEK": {SEK, "SEK"},
		"SGD": {SGD, "SGD"},
		"SHP": {SHP, "SHP"},
		"SLL": {SLL, "SLL"},
		"SOS": {SOS, "SOS"},
		"SRD": {SRD, "SRD"},
		"SSP": {SSP, "SSP"},
		"STD": {STD, "STD"},
		"SYP": {SYP, "SYP"},
		"SZL": {SZL, "SZL"},
		"THB": {THB, "THB"},
		"TJS": {TJS, "TJS"},
		"TMT": {TMT, "TMT"},
		"TND": {TND, "TND"},
		"TOP": {TOP, "TOP"},
		"TRY": {TRY, "TRY"},
		"TTD": {TTD, "TTD"},
		"TWD": {TWD, "TWD"},
		"TZS": {TZS, "TZS"},
		"UAH": {UAH, "UAH"},
		"UGX": {UGX, "UGX"},
		"USD": {USD, "USD"},
		"USN": {USN, "USN"},
		"USS": {USS, "USS"},
		"UYI": {UYI, "UYI"},
		"UYU": {UYU, "UYU"},
		"UZS": {UZS, "UZS"},
		"VEF": {VEF, "VEF"},
		"VND": {VND, "VND"},
		"VUV": {VUV, "VUV"},
		"WST": {WST, "WST"},
		"XAF": {XAF, "XAF"},
		"XAG": {XAG, "XAG"},
		"XAU": {XAU, "XAU"},
		"XBA": {XBA, "XBA"},
		"XBB": {XBB, "XBB"},
		"XBC": {XBC, "XBC"},
		"XBD": {XBD, "XBD"},
		"XCD": {XCD, "XCD"},
		"XDR": {XDR, "XDR"},
		"XFU": {XFU, "XFU"},
		"XOF": {XOF, "XOF"},
		"XPD": {XPD, "XPD"},
		"XPF": {XPF, "XPF"},
		"XPT": {XPT, "XPT"},
		"XTS": {XTS, "XTS"},
		"XXX": {XXX, "XXX"},
		"YER": {YER, "YER"},
		"ZAR": {ZAR, "ZAR"},
		"ZMW": {ZMW, "ZMW"},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			if got := tc.code.String(); got != tc.want {
				t.Errorf("String() = %v, want %v", got, tc.want)
			}
		})
	}
}

func TestCurrencyCode_UnmarshalJSON(t *testing.T) {
	t.Run("ErrUnmarshalJSON_nil", func(t *testing.T) {
		var code CurrencyCode
		wantErr := ErrUnmarshalJSON

		err := code.UnmarshalJSON(nil)
		if !reflect.DeepEqual(wantErr, err) {
			t.Errorf("UnmarshalJSON() error = %v, wantErr %v", err, wantErr)
		}
	})

	t.Run("ErrUnmarshalJSON_nil", func(t *testing.T) {
		var code CurrencyCode
		wantErr := ErrUnmarshalJSON

		err := code.UnmarshalJSON(nil)
		if !reflect.DeepEqual(wantErr, err) {
			t.Errorf("UnmarshalJSON() error = %v, wantErr %v", err, wantErr)
		}
	})

	type tcase struct {
		code    CurrencyCode
		b       []byte
		want    CurrencyCode
		wantErr error
	}

	tests := map[string]tcase{
		"ErrUnmarshalJSON_nil":     {0, nil, 0, ErrUnmarshalJSON},
		"ErrUnmarshalJSON_invalid": {0, []byte("a"), 0, ErrUnmarshalJSON},
		"AED":                      {0, []byte("AED"), AED, nil},
		"AFN":                      {0, []byte("AFN"), AFN, nil},
		"ALL":                      {0, []byte("ALL"), ALL, nil},
		"AMD":                      {0, []byte("AMD"), AMD, nil},
		"ANG":                      {0, []byte("ANG"), ANG, nil},
		"AOA":                      {0, []byte("AOA"), AOA, nil},
		"ARS":                      {0, []byte("ARS"), ARS, nil},
		"AUD":                      {0, []byte("AUD"), AUD, nil},
		"AWG":                      {0, []byte("AWG"), AWG, nil},
		"AZN":                      {0, []byte("AZN"), AZN, nil},
		"BAM":                      {0, []byte("BAM"), BAM, nil},
		"BBD":                      {0, []byte("BBD"), BBD, nil},
		"BDT":                      {0, []byte("BDT"), BDT, nil},
		"BGN":                      {0, []byte("BGN"), BGN, nil},
		"BHD":                      {0, []byte("BHD"), BHD, nil},
		"BIF":                      {0, []byte("BIF"), BIF, nil},
		"BMD":                      {0, []byte("BMD"), BMD, nil},
		"BND":                      {0, []byte("BND"), BND, nil},
		"BOB":                      {0, []byte("BOB"), BOB, nil},
		"BOV":                      {0, []byte("BOV"), BOV, nil},
		"BRL":                      {0, []byte("BRL"), BRL, nil},
		"BSD":                      {0, []byte("BSD"), BSD, nil},
		"BTN":                      {0, []byte("BTN"), BTN, nil},
		"BWP":                      {0, []byte("BWP"), BWP, nil},
		"BYR":                      {0, []byte("BYR"), BYR, nil},
		"BZD":                      {0, []byte("BZD"), BZD, nil},
		"CAD":                      {0, []byte("CAD"), CAD, nil},
		"CDF":                      {0, []byte("CDF"), CDF, nil},
		"CHE":                      {0, []byte("CHE"), CHE, nil},
		"CHF":                      {0, []byte("CHF"), CHF, nil},
		"CHW":                      {0, []byte("CHW"), CHW, nil},
		"CLF":                      {0, []byte("CLF"), CLF, nil},
		"CLP":                      {0, []byte("CLP"), CLP, nil},
		"CNY":                      {0, []byte("CNY"), CNY, nil},
		"COP":                      {0, []byte("COP"), COP, nil},
		"COU":                      {0, []byte("COU"), COU, nil},
		"CRC":                      {0, []byte("CRC"), CRC, nil},
		"CUC":                      {0, []byte("CUC"), CUC, nil},
		"CUP":                      {0, []byte("CUP"), CUP, nil},
		"CVE":                      {0, []byte("CVE"), CVE, nil},
		"CZK":                      {0, []byte("CZK"), CZK, nil},
		"DJF":                      {0, []byte("DJF"), DJF, nil},
		"DKK":                      {0, []byte("DKK"), DKK, nil},
		"DOP":                      {0, []byte("DOP"), DOP, nil},
		"DZD":                      {0, []byte("DZD"), DZD, nil},
		"EGP":                      {0, []byte("EGP"), EGP, nil},
		"ERN":                      {0, []byte("ERN"), ERN, nil},
		"ETB":                      {0, []byte("ETB"), ETB, nil},
		"EUR":                      {0, []byte("EUR"), EUR, nil},
		"FJD":                      {0, []byte("FJD"), FJD, nil},
		"FKP":                      {0, []byte("FKP"), FKP, nil},
		"GBP":                      {0, []byte("GBP"), GBP, nil},
		"GEL":                      {0, []byte("GEL"), GEL, nil},
		"GHS":                      {0, []byte("GHS"), GHS, nil},
		"GIP":                      {0, []byte("GIP"), GIP, nil},
		"GMD":                      {0, []byte("GMD"), GMD, nil},
		"GNF":                      {0, []byte("GNF"), GNF, nil},
		"GTQ":                      {0, []byte("GTQ"), GTQ, nil},
		"GYD":                      {0, []byte("GYD"), GYD, nil},
		"HKD":                      {0, []byte("HKD"), HKD, nil},
		"HNL":                      {0, []byte("HNL"), HNL, nil},
		"HRK":                      {0, []byte("HRK"), HRK, nil},
		"HTG":                      {0, []byte("HTG"), HTG, nil},
		"HUF":                      {0, []byte("HUF"), HUF, nil},
		"IDR":                      {0, []byte("IDR"), IDR, nil},
		"ILS":                      {0, []byte("ILS"), ILS, nil},
		"INR":                      {0, []byte("INR"), INR, nil},
		"IQD":                      {0, []byte("IQD"), IQD, nil},
		"IRR":                      {0, []byte("IRR"), IRR, nil},
		"ISK":                      {0, []byte("ISK"), ISK, nil},
		"JMD":                      {0, []byte("JMD"), JMD, nil},
		"JOD":                      {0, []byte("JOD"), JOD, nil},
		"JPY":                      {0, []byte("JPY"), JPY, nil},
		"KES":                      {0, []byte("KES"), KES, nil},
		"KGS":                      {0, []byte("KGS"), KGS, nil},
		"KHR":                      {0, []byte("KHR"), KHR, nil},
		"KMF":                      {0, []byte("KMF"), KMF, nil},
		"KPW":                      {0, []byte("KPW"), KPW, nil},
		"KRW":                      {0, []byte("KRW"), KRW, nil},
		"KWD":                      {0, []byte("KWD"), KWD, nil},
		"KYD":                      {0, []byte("KYD"), KYD, nil},
		"KZT":                      {0, []byte("KZT"), KZT, nil},
		"LAK":                      {0, []byte("LAK"), LAK, nil},
		"LBP":                      {0, []byte("LBP"), LBP, nil},
		"LKR":                      {0, []byte("LKR"), LKR, nil},
		"LRD":                      {0, []byte("LRD"), LRD, nil},
		"LSL":                      {0, []byte("LSL"), LSL, nil},
		"LTL":                      {0, []byte("LTL"), LTL, nil},
		"LVL":                      {0, []byte("LVL"), LVL, nil},
		"LYD":                      {0, []byte("LYD"), LYD, nil},
		"MAD":                      {0, []byte("MAD"), MAD, nil},
		"MDL":                      {0, []byte("MDL"), MDL, nil},
		"MGA":                      {0, []byte("MGA"), MGA, nil},
		"MKD":                      {0, []byte("MKD"), MKD, nil},
		"MMK":                      {0, []byte("MMK"), MMK, nil},
		"MNT":                      {0, []byte("MNT"), MNT, nil},
		"MOP":                      {0, []byte("MOP"), MOP, nil},
		"MRO":                      {0, []byte("MRO"), MRO, nil},
		"MUR":                      {0, []byte("MUR"), MUR, nil},
		"MVR":                      {0, []byte("MVR"), MVR, nil},
		"MWK":                      {0, []byte("MWK"), MWK, nil},
		"MXN":                      {0, []byte("MXN"), MXN, nil},
		"MXV":                      {0, []byte("MXV"), MXV, nil},
		"MYR":                      {0, []byte("MYR"), MYR, nil},
		"MZN":                      {0, []byte("MZN"), MZN, nil},
		"NAD":                      {0, []byte("NAD"), NAD, nil},
		"NGN":                      {0, []byte("NGN"), NGN, nil},
		"NIO":                      {0, []byte("NIO"), NIO, nil},
		"NOK":                      {0, []byte("NOK"), NOK, nil},
		"NPR":                      {0, []byte("NPR"), NPR, nil},
		"NZD":                      {0, []byte("NZD"), NZD, nil},
		"OMR":                      {0, []byte("OMR"), OMR, nil},
		"PAB":                      {0, []byte("PAB"), PAB, nil},
		"PEN":                      {0, []byte("PEN"), PEN, nil},
		"PGK":                      {0, []byte("PGK"), PGK, nil},
		"PHP":                      {0, []byte("PHP"), PHP, nil},
		"PKR":                      {0, []byte("PKR"), PKR, nil},
		"PLN":                      {0, []byte("PLN"), PLN, nil},
		"PYG":                      {0, []byte("PYG"), PYG, nil},
		"QAR":                      {0, []byte("QAR"), QAR, nil},
		"RON":                      {0, []byte("RON"), RON, nil},
		"RSD":                      {0, []byte("RSD"), RSD, nil},
		"RUB":                      {0, []byte("RUB"), RUB, nil},
		"RWF":                      {0, []byte("RWF"), RWF, nil},
		"SAR":                      {0, []byte("SAR"), SAR, nil},
		"SBD":                      {0, []byte("SBD"), SBD, nil},
		"SCR":                      {0, []byte("SCR"), SCR, nil},
		"SDG":                      {0, []byte("SDG"), SDG, nil},
		"SEK":                      {0, []byte("SEK"), SEK, nil},
		"SGD":                      {0, []byte("SGD"), SGD, nil},
		"SHP":                      {0, []byte("SHP"), SHP, nil},
		"SLL":                      {0, []byte("SLL"), SLL, nil},
		"SOS":                      {0, []byte("SOS"), SOS, nil},
		"SRD":                      {0, []byte("SRD"), SRD, nil},
		"SSP":                      {0, []byte("SSP"), SSP, nil},
		"STD":                      {0, []byte("STD"), STD, nil},
		"SYP":                      {0, []byte("SYP"), SYP, nil},
		"SZL":                      {0, []byte("SZL"), SZL, nil},
		"THB":                      {0, []byte("THB"), THB, nil},
		"TJS":                      {0, []byte("TJS"), TJS, nil},
		"TMT":                      {0, []byte("TMT"), TMT, nil},
		"TND":                      {0, []byte("TND"), TND, nil},
		"TOP":                      {0, []byte("TOP"), TOP, nil},
		"TRY":                      {0, []byte("TRY"), TRY, nil},
		"TTD":                      {0, []byte("TTD"), TTD, nil},
		"TWD":                      {0, []byte("TWD"), TWD, nil},
		"TZS":                      {0, []byte("TZS"), TZS, nil},
		"UAH":                      {0, []byte("UAH"), UAH, nil},
		"UGX":                      {0, []byte("UGX"), UGX, nil},
		"USD":                      {0, []byte("USD"), USD, nil},
		"USN":                      {0, []byte("USN"), USN, nil},
		"USS":                      {0, []byte("USS"), USS, nil},
		"UYI":                      {0, []byte("UYI"), UYI, nil},
		"UYU":                      {0, []byte("UYU"), UYU, nil},
		"UZS":                      {0, []byte("UZS"), UZS, nil},
		"VEF":                      {0, []byte("VEF"), VEF, nil},
		"VND":                      {0, []byte("VND"), VND, nil},
		"VUV":                      {0, []byte("VUV"), VUV, nil},
		"WST":                      {0, []byte("WST"), WST, nil},
		"XAF":                      {0, []byte("XAF"), XAF, nil},
		"XAG":                      {0, []byte("XAG"), XAG, nil},
		"XAU":                      {0, []byte("XAU"), XAU, nil},
		"XBA":                      {0, []byte("XBA"), XBA, nil},
		"XBB":                      {0, []byte("XBB"), XBB, nil},
		"XBC":                      {0, []byte("XBC"), XBC, nil},
		"XBD":                      {0, []byte("XBD"), XBD, nil},
		"XCD":                      {0, []byte("XCD"), XCD, nil},
		"XDR":                      {0, []byte("XDR"), XDR, nil},
		"XFU":                      {0, []byte("XFU"), XFU, nil},
		"XOF":                      {0, []byte("XOF"), XOF, nil},
		"XPD":                      {0, []byte("XPD"), XPD, nil},
		"XPF":                      {0, []byte("XPF"), XPF, nil},
		"XPT":                      {0, []byte("XPT"), XPT, nil},
		"XTS":                      {0, []byte("XTS"), XTS, nil},
		"XXX":                      {0, []byte("XXX"), XXX, nil},
		"YER":                      {0, []byte("YER"), YER, nil},
		"ZAR":                      {0, []byte("ZAR"), ZAR, nil},
		"ZMW":                      {0, []byte("ZMW"), ZMW, nil},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			err := tc.code.UnmarshalJSON(tc.b)
			if tc.wantErr != nil {
				if !reflect.DeepEqual(tc.wantErr, err) {
					t.Errorf("UnmarshalJSON() error = %v, wantErr %v", err, tc.wantErr)
				}
			} else {
				if tc.code != tc.want {
					t.Errorf("UnmarshalJSON() got = %v, want %v", tc.code, tc.want)
				}
			}
		})
	}
}

func TestCurrencyCode_UnmarshalText(t *testing.T) {
	type tcase struct {
		code    CurrencyCode
		want    CurrencyCode
		wantErr error
	}

	tests := map[string]tcase{
		"AED": {0, AED, nil},
		"AFN": {0, AFN, nil},
		"ALL": {0, ALL, nil},
		"AMD": {0, AMD, nil},
		"ANG": {0, ANG, nil},
		"AOA": {0, AOA, nil},
		"ARS": {0, ARS, nil},
		"AUD": {0, AUD, nil},
		"AWG": {0, AWG, nil},
		"AZN": {0, AZN, nil},
		"BAM": {0, BAM, nil},
		"BBD": {0, BBD, nil},
		"BDT": {0, BDT, nil},
		"BGN": {0, BGN, nil},
		"BHD": {0, BHD, nil},
		"BIF": {0, BIF, nil},
		"BMD": {0, BMD, nil},
		"BND": {0, BND, nil},
		"BOB": {0, BOB, nil},
		"BOV": {0, BOV, nil},
		"BRL": {0, BRL, nil},
		"BSD": {0, BSD, nil},
		"BTN": {0, BTN, nil},
		"BWP": {0, BWP, nil},
		"BYR": {0, BYR, nil},
		"BZD": {0, BZD, nil},
		"CAD": {0, CAD, nil},
		"CDF": {0, CDF, nil},
		"CHE": {0, CHE, nil},
		"CHF": {0, CHF, nil},
		"CHW": {0, CHW, nil},
		"CLF": {0, CLF, nil},
		"CLP": {0, CLP, nil},
		"CNY": {0, CNY, nil},
		"COP": {0, COP, nil},
		"COU": {0, COU, nil},
		"CRC": {0, CRC, nil},
		"CUC": {0, CUC, nil},
		"CUP": {0, CUP, nil},
		"CVE": {0, CVE, nil},
		"CZK": {0, CZK, nil},
		"DJF": {0, DJF, nil},
		"DKK": {0, DKK, nil},
		"DOP": {0, DOP, nil},
		"DZD": {0, DZD, nil},
		"EGP": {0, EGP, nil},
		"ERN": {0, ERN, nil},
		"ETB": {0, ETB, nil},
		"EUR": {0, EUR, nil},
		"FJD": {0, FJD, nil},
		"FKP": {0, FKP, nil},
		"GBP": {0, GBP, nil},
		"GEL": {0, GEL, nil},
		"GHS": {0, GHS, nil},
		"GIP": {0, GIP, nil},
		"GMD": {0, GMD, nil},
		"GNF": {0, GNF, nil},
		"GTQ": {0, GTQ, nil},
		"GYD": {0, GYD, nil},
		"HKD": {0, HKD, nil},
		"HNL": {0, HNL, nil},
		"HRK": {0, HRK, nil},
		"HTG": {0, HTG, nil},
		"HUF": {0, HUF, nil},
		"IDR": {0, IDR, nil},
		"ILS": {0, ILS, nil},
		"INR": {0, INR, nil},
		"IQD": {0, IQD, nil},
		"IRR": {0, IRR, nil},
		"ISK": {0, ISK, nil},
		"JMD": {0, JMD, nil},
		"JOD": {0, JOD, nil},
		"JPY": {0, JPY, nil},
		"KES": {0, KES, nil},
		"KGS": {0, KGS, nil},
		"KHR": {0, KHR, nil},
		"KMF": {0, KMF, nil},
		"KPW": {0, KPW, nil},
		"KRW": {0, KRW, nil},
		"KWD": {0, KWD, nil},
		"KYD": {0, KYD, nil},
		"KZT": {0, KZT, nil},
		"LAK": {0, LAK, nil},
		"LBP": {0, LBP, nil},
		"LKR": {0, LKR, nil},
		"LRD": {0, LRD, nil},
		"LSL": {0, LSL, nil},
		"LTL": {0, LTL, nil},
		"LVL": {0, LVL, nil},
		"LYD": {0, LYD, nil},
		"MAD": {0, MAD, nil},
		"MDL": {0, MDL, nil},
		"MGA": {0, MGA, nil},
		"MKD": {0, MKD, nil},
		"MMK": {0, MMK, nil},
		"MNT": {0, MNT, nil},
		"MOP": {0, MOP, nil},
		"MRO": {0, MRO, nil},
		"MUR": {0, MUR, nil},
		"MVR": {0, MVR, nil},
		"MWK": {0, MWK, nil},
		"MXN": {0, MXN, nil},
		"MXV": {0, MXV, nil},
		"MYR": {0, MYR, nil},
		"MZN": {0, MZN, nil},
		"NAD": {0, NAD, nil},
		"NGN": {0, NGN, nil},
		"NIO": {0, NIO, nil},
		"NOK": {0, NOK, nil},
		"NPR": {0, NPR, nil},
		"NZD": {0, NZD, nil},
		"OMR": {0, OMR, nil},
		"PAB": {0, PAB, nil},
		"PEN": {0, PEN, nil},
		"PGK": {0, PGK, nil},
		"PHP": {0, PHP, nil},
		"PKR": {0, PKR, nil},
		"PLN": {0, PLN, nil},
		"PYG": {0, PYG, nil},
		"QAR": {0, QAR, nil},
		"RON": {0, RON, nil},
		"RSD": {0, RSD, nil},
		"RUB": {0, RUB, nil},
		"RWF": {0, RWF, nil},
		"SAR": {0, SAR, nil},
		"SBD": {0, SBD, nil},
		"SCR": {0, SCR, nil},
		"SDG": {0, SDG, nil},
		"SEK": {0, SEK, nil},
		"SGD": {0, SGD, nil},
		"SHP": {0, SHP, nil},
		"SLL": {0, SLL, nil},
		"SOS": {0, SOS, nil},
		"SRD": {0, SRD, nil},
		"SSP": {0, SSP, nil},
		"STD": {0, STD, nil},
		"SYP": {0, SYP, nil},
		"SZL": {0, SZL, nil},
		"THB": {0, THB, nil},
		"TJS": {0, TJS, nil},
		"TMT": {0, TMT, nil},
		"TND": {0, TND, nil},
		"TOP": {0, TOP, nil},
		"TRY": {0, TRY, nil},
		"TTD": {0, TTD, nil},
		"TWD": {0, TWD, nil},
		"TZS": {0, TZS, nil},
		"UAH": {0, UAH, nil},
		"UGX": {0, UGX, nil},
		"USD": {0, USD, nil},
		"USN": {0, USN, nil},
		"USS": {0, USS, nil},
		"UYI": {0, UYI, nil},
		"UYU": {0, UYU, nil},
		"UZS": {0, UZS, nil},
		"VEF": {0, VEF, nil},
		"VND": {0, VND, nil},
		"VUV": {0, VUV, nil},
		"WST": {0, WST, nil},
		"XAF": {0, XAF, nil},
		"XAG": {0, XAG, nil},
		"XAU": {0, XAU, nil},
		"XBA": {0, XBA, nil},
		"XBB": {0, XBB, nil},
		"XBC": {0, XBC, nil},
		"XBD": {0, XBD, nil},
		"XCD": {0, XCD, nil},
		"XDR": {0, XDR, nil},
		"XFU": {0, XFU, nil},
		"XOF": {0, XOF, nil},
		"XPD": {0, XPD, nil},
		"XPF": {0, XPF, nil},
		"XPT": {0, XPT, nil},
		"XTS": {0, XTS, nil},
		"XXX": {0, XXX, nil},
		"YER": {0, YER, nil},
		"ZAR": {0, ZAR, nil},
		"ZMW": {0, ZMW, nil},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			err := tc.code.UnmarshalText([]byte(tc.want.String()))
			if tc.wantErr != nil {
				if !reflect.DeepEqual(tc.wantErr, err) {
					t.Errorf("UnmarshalText() error = %v, wantErr %v", err, tc.wantErr)
				}
			} else {
				if tc.code != tc.want {
					t.Errorf("UnmarshalText() got = %v, want %v", tc.code, tc.want)
				}
			}
		})
	}
}

func TestStringToCurrencyCode(t *testing.T) {
	type tcase struct {
		strCode string
		want    CurrencyCode
		wantErr error
	}

	tests := map[string]tcase{
		"Err1": {"", 0, ErrInvalidStringCode},
		"Err2": {"AE", 0, ErrInvalidStringCode},
		"Err3": {"AAA", 0, ErrInvalidStringCode},
		"Err4": {"AAAA", 0, ErrInvalidStringCode},
		"AED":  {"AED", AED, nil},
		"AFN":  {"AFN", AFN, nil},
		"ALL":  {"ALL", ALL, nil},
		"AMD":  {"AMD", AMD, nil},
		"ANG":  {"ANG", ANG, nil},
		"AOA":  {"AOA", AOA, nil},
		"ARS":  {"ARS", ARS, nil},
		"AUD":  {"AUD", AUD, nil},
		"AWG":  {"AWG", AWG, nil},
		"AZN":  {"AZN", AZN, nil},
		"BAM":  {"BAM", BAM, nil},
		"BBD":  {"BBD", BBD, nil},
		"BDT":  {"BDT", BDT, nil},
		"BGN":  {"BGN", BGN, nil},
		"BHD":  {"BHD", BHD, nil},
		"BIF":  {"BIF", BIF, nil},
		"BMD":  {"BMD", BMD, nil},
		"BND":  {"BND", BND, nil},
		"BOB":  {"BOB", BOB, nil},
		"BOV":  {"BOV", BOV, nil},
		"BRL":  {"BRL", BRL, nil},
		"BSD":  {"BSD", BSD, nil},
		"BTN":  {"BTN", BTN, nil},
		"BWP":  {"BWP", BWP, nil},
		"BYR":  {"BYR", BYR, nil},
		"BZD":  {"BZD", BZD, nil},
		"CAD":  {"CAD", CAD, nil},
		"CDF":  {"CDF", CDF, nil},
		"CHE":  {"CHE", CHE, nil},
		"CHF":  {"CHF", CHF, nil},
		"CHW":  {"CHW", CHW, nil},
		"CLF":  {"CLF", CLF, nil},
		"CLP":  {"CLP", CLP, nil},
		"CNY":  {"CNY", CNY, nil},
		"COP":  {"COP", COP, nil},
		"COU":  {"COU", COU, nil},
		"CRC":  {"CRC", CRC, nil},
		"CUC":  {"CUC", CUC, nil},
		"CUP":  {"CUP", CUP, nil},
		"CVE":  {"CVE", CVE, nil},
		"CZK":  {"CZK", CZK, nil},
		"DJF":  {"DJF", DJF, nil},
		"DKK":  {"DKK", DKK, nil},
		"DOP":  {"DOP", DOP, nil},
		"DZD":  {"DZD", DZD, nil},
		"EGP":  {"EGP", EGP, nil},
		"ERN":  {"ERN", ERN, nil},
		"ETB":  {"ETB", ETB, nil},
		"EUR":  {"EUR", EUR, nil},
		"FJD":  {"FJD", FJD, nil},
		"FKP":  {"FKP", FKP, nil},
		"GBP":  {"GBP", GBP, nil},
		"GEL":  {"GEL", GEL, nil},
		"GHS":  {"GHS", GHS, nil},
		"GIP":  {"GIP", GIP, nil},
		"GMD":  {"GMD", GMD, nil},
		"GNF":  {"GNF", GNF, nil},
		"GTQ":  {"GTQ", GTQ, nil},
		"GYD":  {"GYD", GYD, nil},
		"HKD":  {"HKD", HKD, nil},
		"HNL":  {"HNL", HNL, nil},
		"HRK":  {"HRK", HRK, nil},
		"HTG":  {"HTG", HTG, nil},
		"HUF":  {"HUF", HUF, nil},
		"IDR":  {"IDR", IDR, nil},
		"ILS":  {"ILS", ILS, nil},
		"INR":  {"INR", INR, nil},
		"IQD":  {"IQD", IQD, nil},
		"IRR":  {"IRR", IRR, nil},
		"ISK":  {"ISK", ISK, nil},
		"JMD":  {"JMD", JMD, nil},
		"JOD":  {"JOD", JOD, nil},
		"JPY":  {"JPY", JPY, nil},
		"KES":  {"KES", KES, nil},
		"KGS":  {"KGS", KGS, nil},
		"KHR":  {"KHR", KHR, nil},
		"KMF":  {"KMF", KMF, nil},
		"KPW":  {"KPW", KPW, nil},
		"KRW":  {"KRW", KRW, nil},
		"KWD":  {"KWD", KWD, nil},
		"KYD":  {"KYD", KYD, nil},
		"KZT":  {"KZT", KZT, nil},
		"LAK":  {"LAK", LAK, nil},
		"LBP":  {"LBP", LBP, nil},
		"LKR":  {"LKR", LKR, nil},
		"LRD":  {"LRD", LRD, nil},
		"LSL":  {"LSL", LSL, nil},
		"LTL":  {"LTL", LTL, nil},
		"LVL":  {"LVL", LVL, nil},
		"LYD":  {"LYD", LYD, nil},
		"MAD":  {"MAD", MAD, nil},
		"MDL":  {"MDL", MDL, nil},
		"MGA":  {"MGA", MGA, nil},
		"MKD":  {"MKD", MKD, nil},
		"MMK":  {"MMK", MMK, nil},
		"MNT":  {"MNT", MNT, nil},
		"MOP":  {"MOP", MOP, nil},
		"MRO":  {"MRO", MRO, nil},
		"MUR":  {"MUR", MUR, nil},
		"MVR":  {"MVR", MVR, nil},
		"MWK":  {"MWK", MWK, nil},
		"MXN":  {"MXN", MXN, nil},
		"MXV":  {"MXV", MXV, nil},
		"MYR":  {"MYR", MYR, nil},
		"MZN":  {"MZN", MZN, nil},
		"NAD":  {"NAD", NAD, nil},
		"NGN":  {"NGN", NGN, nil},
		"NIO":  {"NIO", NIO, nil},
		"NOK":  {"NOK", NOK, nil},
		"NPR":  {"NPR", NPR, nil},
		"NZD":  {"NZD", NZD, nil},
		"OMR":  {"OMR", OMR, nil},
		"PAB":  {"PAB", PAB, nil},
		"PEN":  {"PEN", PEN, nil},
		"PGK":  {"PGK", PGK, nil},
		"PHP":  {"PHP", PHP, nil},
		"PKR":  {"PKR", PKR, nil},
		"PLN":  {"PLN", PLN, nil},
		"PYG":  {"PYG", PYG, nil},
		"QAR":  {"QAR", QAR, nil},
		"RON":  {"RON", RON, nil},
		"RSD":  {"RSD", RSD, nil},
		"RUB":  {"RUB", RUB, nil},
		"RWF":  {"RWF", RWF, nil},
		"SAR":  {"SAR", SAR, nil},
		"SBD":  {"SBD", SBD, nil},
		"SCR":  {"SCR", SCR, nil},
		"SDG":  {"SDG", SDG, nil},
		"SEK":  {"SEK", SEK, nil},
		"SGD":  {"SGD", SGD, nil},
		"SHP":  {"SHP", SHP, nil},
		"SLL":  {"SLL", SLL, nil},
		"SOS":  {"SOS", SOS, nil},
		"SRD":  {"SRD", SRD, nil},
		"SSP":  {"SSP", SSP, nil},
		"STD":  {"STD", STD, nil},
		"SYP":  {"SYP", SYP, nil},
		"SZL":  {"SZL", SZL, nil},
		"THB":  {"THB", THB, nil},
		"TJS":  {"TJS", TJS, nil},
		"TMT":  {"TMT", TMT, nil},
		"TND":  {"TND", TND, nil},
		"TOP":  {"TOP", TOP, nil},
		"TRY":  {"TRY", TRY, nil},
		"TTD":  {"TTD", TTD, nil},
		"TWD":  {"TWD", TWD, nil},
		"TZS":  {"TZS", TZS, nil},
		"UAH":  {"UAH", UAH, nil},
		"UGX":  {"UGX", UGX, nil},
		"USD":  {"USD", USD, nil},
		"USN":  {"USN", USN, nil},
		"USS":  {"USS", USS, nil},
		"UYI":  {"UYI", UYI, nil},
		"UYU":  {"UYU", UYU, nil},
		"UZS":  {"UZS", UZS, nil},
		"VEF":  {"VEF", VEF, nil},
		"VND":  {"VND", VND, nil},
		"VUV":  {"VUV", VUV, nil},
		"WST":  {"WST", WST, nil},
		"XAF":  {"XAF", XAF, nil},
		"XAG":  {"XAG", XAG, nil},
		"XAU":  {"XAU", XAU, nil},
		"XBA":  {"XBA", XBA, nil},
		"XBB":  {"XBB", XBB, nil},
		"XBC":  {"XBC", XBC, nil},
		"XBD":  {"XBD", XBD, nil},
		"XCD":  {"XCD", XCD, nil},
		"XDR":  {"XDR", XDR, nil},
		"XFU":  {"XFU", XFU, nil},
		"XOF":  {"XOF", XOF, nil},
		"XPD":  {"XPD", XPD, nil},
		"XPF":  {"XPF", XPF, nil},
		"XPT":  {"XPT", XPT, nil},
		"XTS":  {"XTS", XTS, nil},
		"XXX":  {"XXX", XXX, nil},
		"YER":  {"YER", YER, nil},
		"ZAR":  {"ZAR", ZAR, nil},
		"ZMW":  {"ZMW", ZMW, nil},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			got, err := StringToCurrencyCode(tc.strCode)
			if tc.wantErr != nil {
				if !reflect.DeepEqual(tc.wantErr, err) {
					t.Errorf("StringToCurrencyCode() error = %v, wantErr %v", err, tc.wantErr)
				}
			} else {
				if got != tc.want {
					t.Errorf("StringToCurrencyCode() got = %v, want %v", got, tc.want)
				}
			}
		})
	}
}
